# Standards: 0.1
---
- name: Install required packages
  loop: "{{ mariadb_packages }}"
  package:
    name: "{{ item }}"
    state: present
  tags:
    - mariadb

- name: Create temp directory
  when: mariadb_temp_directory | default(False)
  file:
    path: "{{ mariadb_temp_directory }}"
    owner: root
    group: root
    mode: u=rwx,g=rwx,o=rwx
    state: directory
  tags:
    - mariadb

- name: Fix data permissions
  file:
    path: /var/lib/mysql
    owner: mysql
    group: mysql
  tags:
    - mariadb

- name: Write override config
  notify:
    - Restart mariadb
  template:
    src: config.j2
    dest: /etc/mysql/mariadb.conf.d/99-override.cnf
  tags:
    - mariadb

- name: Start mariadb service
  systemd:
    name: mariadb
    state: started
    daemon_reload: True
    masked: False
    enabled: True
  tags:
    - mariadb

- name: Update root account
  no_log: True
  loop: "{{ mariadb_root_hosts }}"
  mysql_user:
    name: "{{ mariadb_root_username }}"
    password: "{{ mariadb_root_password }}"
    host: "{{ item }}"
    check_implicit_admin: True
    login_unix_socket: /var/run/mysqld/mysqld.sock
    login_user: "{{ mariadb_root_username }}"
    login_password: "{{ mariadb_root_password }}"
    state: present
  tags:
    - mariadb

- name: Write debian config
  template:
    src: debian.j2
    dest: /etc/mysql/debian.cnf
    owner: root
    group: root
    mode: u=rw,g=,o=
  tags:
    - mariadb

- name: Write auth config
  template:
    src: auth.j2
    dest: /root/.my.cnf
    owner: root
    group: root
    mode: u=rw,g=,o=
  tags:
    - mariadb

- name: Remove anonymous user
  no_log: True
  mysql_user:
    name: ""
    host_all: True
    state: absent
    login_unix_socket: /var/run/mysqld/mysqld.sock
  tags:
    - mariadb

- name: Remove test database
  mysql_db:
    name: test
    state: absent
    login_unix_socket: /var/run/mysqld/mysqld.sock
  tags:
    - mariadb

- name: Create defined databases
  loop: "{{ mariadb_global_databases + mariadb_extra_databases }}"
  loop_control:
    label: "{{ item.name }}"
  mysql_db:
    name: "{{ item.name }}"
    collation: "{{ item.collation | default(omit) }}"
    encoding: "{{ item.encoding | default(omit) }}"
    state: "{{ item.state | default('present') }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
  tags:
    - mariadb

- name: Create defined users
  no_log: True
  loop: "{{ mariadb_global_users + mariadb_extra_users }}"
  loop_control:
    label: "{{ item.name }}"
  mysql_user:
    name: "{{ item.name }}"
    password: "{{ item.password | default(omit) }}"
    host: "{{ item.host | default('%') }}"
    priv: "{{ item.priv | default(omit) }}"
    update_password: "{{ item.update_password | default('always') }}"
    encrypted: "{{ item.encrypted | default(False) }}"
    state: "{{ item.state | default('present') }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
  tags:
    - mariadb

- name: Write backup script
  when: mariadb_backup_enabled
  template:
    src: backup.j2
    dest: /usr/local/bin/mariadb-backup
    owner: root
    group: root
    mode: u=rwx,g=rwx,o=
  tags:
    - mariadb

- name: Remove backup script
  when: not mariadb_backup_enabled
  file:
    path: /usr/local/bin/mariadb-backup
    state: absent
  tags:
    - mariadb

- name: Create backup cronjobs
  cron:
    name: mariadb backup
    special_time: "{{ mariadb_backup_cron }}"
    job: /usr/bin/cronic /usr/local/bin/mariadb-backup
    state: "{{ 'present' if mariadb_backup_enabled else 'absent' }}"
  tags:
    - mariadb

- name: Include exporter tasks
  when: mariadb_exporter_enabled | default(False)
  include: exporter.yml
  tags:
    - mariadb
    - mariadb-exporter

...
