# Standards: 0.1
---
- name: Restart mariadb
  systemd:
    name: mariadb
    state: restarted
    daemon_reload: True

- name: Restart mariadb-exporter
  systemd:
    name: mariadb-exporter
    state: restarted
    daemon_reload: True

...
