---
- name: Restart mariadb
  ansible.builtin.systemd:
    name: mariadb
    state: restarted
    daemon_reload: True

- name: Restart mariadb-exporter
  ansible.builtin.systemd:
    name: mariadb-exporter
    state: restarted
    daemon_reload: True

...
